bazaar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.views import static
from django.views.generic import TemplateView

from users.views import SignUpView
from users.views import JoinCommunity, RegistrationClosed
from commons.views import home

from search.views import BazaarSearch

urlpatterns = [
    path('', home, name='home'),
    path('welcome/', BazaarSearch.as_view(), name='welcome'),
    path('<locale>/signup/', SignUpView.as_view(), name='signup'),
    path('<locale>/referral/<code>/signup/', SignUpView.as_view(), name='r_signup'),

    path('', include('django.contrib.auth.urls')),
    path('search/', include('haystack.urls')),
    path('password/', include('users.url.password')),
    path('user/', include('users.urls', namespace='user')),
    path('item/', include('items.urls', namespace='item')),
    path('store/', include('store.urls.store', namespace='store')),
    path('stock/', include('store.urls.stock', namespace='stock')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('offer/', include('interest.urls.offer', namespace='offer')),
    path('bargain/', include('interest.urls.bargain', namespace='bargain')),
    path('bookmark/', include('interest.urls.bookmark', namespace='bookmark')),
    path('order/', include('interest.urls.order', namespace='order')),

    path('admin/', admin.site.urls),
    path('join/', JoinCommunity.as_view(), name='join'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('intro/', TemplateView.as_view(template_name='intro.html'), name='intro'),
    path('registration/closed/', RegistrationClosed.as_view(), name='closed'),

]

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', static.serve,
                        {'document_root': settings.MEDIA_ROOT, }
                        ),
                    ]

items/urls.py
from django.urls import path

# My imports -----------------------------------------------------------------
from django.views.generic import TemplateView

from .views import AddItem, ItemInventory, item_home
from .views import ItemDetails, ItemSort
from .views import EditItem, RemoveItem
from .views import ItemReserved, ListItems


from search.views import ItemSearch
from interest.views import AddOffer

app_name = 'item'
urlpatterns = [
    path('', item_home, name='home'),
    path('sort/', TemplateView.as_view(template_name='items/category.html'), name='sort'),
    path('search/', ItemSearch.as_view(), name='search'),

    path('add/', AddItem.as_view(), name='add'),
    path('all/', ListItems.as_view(), name='all'),
    path('inventory/', ItemInventory.as_view(), name='inventory'),

    path('<int:pk>/', ItemDetails.as_view(), name='details'),
    path('<int:pk>/edit/', EditItem.as_view(), name='update'),
    path('<int:pk>/remove/', RemoveItem.as_view(), name='remove'),
    path('<int:pk>/reserved/', ItemReserved.as_view(), name='reserved'),
    path('<int:pk>/interested/', AddOffer.as_view(), name='interested'),

    path('<str:category>/', ItemSort.as_view(), name='category'),
]

users/urls.py
from django.urls import path

from review.views import create_review

from .views import UpdateProfile, DeleteView
from .views import ProfileDetails


app_name = 'user'
urlpatterns = [
    path('<int:pk>/', ProfileDetails.as_view(), name='details'),
    path('<int:pk>/delete/', DeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', UpdateProfile.as_view(), name='update'),
    path('<int:pk>/review/', create_review, name='review_create'),

]

store/models.py
from django.db import models

# Create your models here.
# My imports -----------------------------------------------------------------
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

import cloudinary
from cloudinary.models import CloudinaryField

from django.dispatch import receiver
from django.db.models.signals import pre_delete

from .constants import CATEGORIES
# =======================================================================

DOMAIN = getattr(settings, 'DOMAIN', 'localhost')


def front_photo_path(instance, filename):
    return '/'.join(['item', str(instance.pk), 'front-'+str(filename)])


def back_photo_path(instance, filename):
    return '/'.join(['item', str(instance.pk), 'back-'+str(filename)])

# =======================================================================


class Store(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(default='', blank=True)
    owner = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, )
    is_verified = models.BooleanField(default=False, blank=True)

    def get_absolute_url(self):
        return reverse("store:details", kwargs={'pk': self.pk})

    def get_direct_url(self):
        return DOMAIN+reverse("store:details", kwargs={'pk': self.pk})


class Stock(models.Model):
    name = models.CharField(max_length=100,)
    description = models.TextField(default='', blank=True)
    price = models.PositiveSmallIntegerField()
    category = models.CharField(max_length=25, choices=CATEGORIES)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, )
    quantity = models.PositiveSmallIntegerField(default=2)

    date_added = models.DateTimeField(auto_now_add=True, blank=True,)
    orders = models.ManyToManyField(get_user_model(), related_name='orders', )

    def __str__(self):
        return "%(category)s: %(name)s" % ({'category': self.category,
                                            'name': self.name})

    def get_absolute_url(self):
        return reverse('stock:details', kwargs={'pk': self.pk})

    def get_return_url(self):
        return reverse('stock', kwargs={'pk': self.store.pk})

    def get_description(self):
        return self.description.strip().split('**')

    def get_direct_url(self):
        return DOMAIN+reverse("stock:details", kwargs={'pk': self.pk})


class CloudinaryPhoto(models.Model):
    image = CloudinaryField('image')
    stock = models.OneToOneField(Stock, on_delete=models.CASCADE, )


@receiver(pre_delete, sender=CloudinaryPhoto)
def photo_delete(sender, instance, **kwargs):
    cloudinary.uploader.destroy(instance.image.public_id)

store/forms.py
from django import forms
from django.template.loader import render_to_string
from django.forms import ModelForm

from .models import Store, Stock
from .models import CloudinaryPhoto

# ===================================================================


class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = ('name', 'description', )
        labels = {'name': 'Store name', }


class StockForm(forms.ModelForm):
    iTemplate = 'items/item_description.txt'
    description = forms.CharField(help_text="**Add information that more accurately Describes your Item",
                                  initial=render_to_string(iTemplate).strip(),
                                  widget=forms.Textarea(attrs={'cols': 35, 'rows': 4, }),
                                  )

    class Meta:
        model = Stock
        fields = ('category', 'name', 'description', 'quantity', 'price')
        labels = {'name': 'Item name', }


class StockUpdateForm(StockForm):
    class Meta(StockForm.Meta):
        fields = ('category', 'name', 'description', 'quantity', 'price',)


class CloudinaryPhotoForm(ModelForm):
    class Meta:
        model = CloudinaryPhoto
        fields = ('image', )

interest/views.py
from django.shortcuts import render, redirect


# Create your views here.
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.views.generic import CreateView, UpdateView
from django.views.generic import ListView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Offer, Bookmarks, Bargain, Order
from .forms import OfferForm, BargainForm, OrderForm

from items.models import Item
from store.models import Stock

# ===================================================================


def charge(bid):
    """This function calculates fees for trnxs."""
    rate = 3.33
    return bid * rate / 100


@login_required
def add_bookmark(request, pk):
    item = Item.objects.get(pk=pk)
    bookmarks, created = Bookmarks.objects.get_or_create(owner=request.user)
    bookmarks.bookmarked.add(item)
    bookmarks.save()
    return redirect(item.get_absolute_url())


@login_required
def remove_bookmark(request, pk):
    item = Item.objects.get(pk=pk)
    bookmarks, created = Bookmarks.objects.get_or_create(owner=request.user)
    bookmarks.bookmarked.remove(item)
    bookmarks.save()
    return redirect(item.get_absolute_url())


@login_required
def get_bookmarks(request):
    bookmarks, created = Bookmarks.objects.get_or_create(owner=request.user)
    return render(request, 'bookmarks/list.html', {'bookmarks': bookmarks})


class AddOffer(LoginRequiredMixin, CreateView):
    model = Offer
    form_class = OfferForm
    login_url = 'login'
    context_object_name = 'offer'
    template_name = 'interest/form.html'

    def form_valid(self, form):
        form.instance.item = Item.objects.get(pk=self.kwargs['pk'])
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Add'
        kwargs['interest'] = 'Offer'
        context = super(AddOffer, self).get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        item = Item.objects.get(pk=self.kwargs['pk'])
        if item.owner == self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class UpdateOffer(LoginRequiredMixin, UpdateView):
    model = Offer
    form_class = OfferForm
    login_url = 'login'
    context_object_name = 'offer'
    template_name = 'interest/form.html'

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Update'
        kwargs['interest'] = 'Offer'
        context = super(UpdateOffer, self).get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        offer = self.get_object()
        if offer.owner != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class DeleteOffer(LoginRequiredMixin, DeleteView):
    model = Offer
    login_url = 'login'
    template_name = 'interest/delete.html'
    success_url = reverse_lazy('home')
    context_object_name = 'offer'

    def dispatch(self, request, *args, **kwargs):
        offer = self.get_object()
        if offer.owner != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class MyOffers(LoginRequiredMixin, ListView):
    model = Offer
    login_url = 'login'
    template_name = 'interest/list.html'
    context_object_name = 'offers'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(owner=self.request.user)
        return queryset


@login_required
def accept_offer(request, pk):
    offer = Offer.objects.get(pk=pk)
    if request.user == offer.item.owner:
        offer.accepted = True
        offer.item.available = False
        offer.item.booked_for = request.user
        offer.item.save()
        offer.save()
    return redirect(offer.item.get_absolute_url())


@login_required
def cancel_offer(request, pk):
    offer = Offer.objects.get(pk=pk)
    if request.user == offer.item.owner or offer.owner == request.user:
        offer.accepted = False
        offer.item.available = True
        offer.item.save()
        offer.save()
        if offer.bargaindeposit:
            offer.bargaindeposit.delete()
    return redirect(offer.item.get_absolute_url())


class MakeBargain(LoginRequiredMixin, CreateView):
    model = Bargain
    form_class = BargainForm
    login_url = 'login'
    context_object_name = 'bargain'
    template_name = 'interest/form.html'

    def form_valid(self, form):
        form.instance.offer = Offer.objects.get(pk=self.kwargs['pk'])
        form.instance.seller = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Make'
        kwargs['interest'] = 'Bargain'
        context = super(MakeBargain, self).get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        offer = Offer.objects.get(pk=self.kwargs['pk'])
        if offer.item.owner != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class UpdateBargain(LoginRequiredMixin, UpdateView):
    model = Bargain
    form_class = BargainForm
    login_url = 'login'
    context_object_name = 'bargain'
    template_name = 'interest/form.html'

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Update'
        kwargs['interest'] = 'Bargain'
        context = super(UpdateBargain, self).get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        bargain = self.get_object()
        if bargain.seller != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class DeleteBargain(LoginRequiredMixin, DeleteView):
    model = Bargain
    login_url = 'login'
    template_name = 'interest/delete.html'
    context_object_name = 'bargain'

    def dispatch(self, request, *args, **kwargs):
        bargain = self.get_object()
        if bargain.seller != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


@login_required
def accept_bargain(request, pk):
    offer = Offer.objects.get(pk=pk)
    if request.user == offer.owner:
        offer.offer = offer.bargain.bargain
        offer.save()
        offer.bargain.delete()
    return redirect(offer.item.get_absolute_url())


class AddOrder(LoginRequiredMixin, CreateView):
    model = Order
    form_class = OrderForm
    login_url = 'login'
    context_object_name = 'order'
    template_name = 'interest/form.html'

    def form_valid(self, form):
        form.instance.stock = Stock.objects.get(pk=self.kwargs['pk'])
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Make'
        kwargs['interest'] = 'Order'
        context = super(AddOrder, self).get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        stock = Stock.objects.get(pk=self.kwargs['pk'])
        if stock.store.owner == self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class UpdateOrder(LoginRequiredMixin, UpdateView):
    model = Order
    form_class = OrderForm
    login_url = 'login'
    context_object_name = 'order'
    template_name = 'interest/form.html'

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Update'
        kwargs['interest'] = 'Order'
        context = super(UpdateOrder, self).get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        order = self.get_object()
        if order.owner != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class DeleteOrder(LoginRequiredMixin, DeleteView):
    model = Order
    login_url = 'login'
    template_name = 'interest/delete.html'
    success_url = reverse_lazy('home')
    context_object_name = 'order'

    def dispatch(self, request, *args, **kwargs):
        order = self.get_object()
        if order.owner == self.request.user or order.stock.store.owner == self.request.user:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class MyOrders(LoginRequiredMixin, ListView):
    model = Order
    login_url = 'login'
    template_name = 'interest/list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(owner=self.request.user)
        return queryset


@login_required
def accept_order(request, pk):
    order = Order.objects.get(pk=pk)
    if order.quantity < order.stock.quantity and order.accepted is False:
        if request.user == order.stock.store.owner:
            order.stock.quantity -= order.quantity
            order.accepted = True
            order.stock.save()
            order.save()
    return redirect(order.stock.get_absolute_url())

store/templates/stock/all.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %} Available Items - {{ block.super }}{% endblock %}
{% block header %}
    {{ block.super }}
{% endblock header %}
{% block content %}
    <div class="row clearfix">
        <div class="col-md-12 column">
            <br><br>
            <text class="h2 button">Available Stock</text>
            {% if items %}
                {% for item in items %}
                <hr>
            <fieldset>
                <h3 style="text-transform:uppercase;">
                    <a href="{% url 'item:details' pk=item.pk %}">
                        {{ item.name }}
                    </a>
                    <br>
                </h3>
                <strong style="font-size: 2rem; color: orange">Owner</strong><br>
                <span class="glyphicon glyphicon-adjust" aria-hidden="true"></span>
                <b>Gender: </b>{{ item.owner.gender.capitalize }}<br>
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                <b>Rating: </b>{{ item.owner.userrating.current_rating }} Star{{ profile.userrating|pluralize }}<br>
                <text style="font-size: 13px;">
                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                    <b>Last seen</b>: {{ item.owner.last_login }}
                </text><br><br>
                <strong style="font-size: 2rem; color: orange">Item</strong><br>
                {% if user.is_authenticated is False %}
                <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                <b>Location: </b>{{ item.owner.locale.upper }}<br>
                {% endif %}
                <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
                <b>Category: </b>{{ item.category }}<br>
                <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
                <b>Interest: </b>{{ item.offer_set.count }}
                Offer{{ item.offer_set.count|pluralize }}<br>
                <b>Available: </b>
                {% if item.available %}
                <span class="glyphicon glyphicon-ok" style="color:green;" aria-hidden="true"></span>
                {% else %}
                <span class="glyphicon glyphicon-remove" style="color:red;"  aria-hidden="true"></span>
                {% endif %}
                <br>
                {% endfor %}
            </fieldset><br><br>
            {% else %}
            <hr>
            No items to show!
            {% endif %}
        </div>
    </div>
{% endblock content %}

store/templates/stock/delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
    Remove Stock - {{ block.super }}
{% endblock title %}
{% block content %}
    {% if user.is_authenticated %}
    <h1>Remove Stock</h1>
    <p>Are you sure you want to remove
        <b>Stock: {{ object.name }}</b>?
    </p>
        <form action="" method="post">
            {% csrf_token %}
            {% buttons %}
                <button type="submit" class="btn btn-danger">
                    Yes! remove
                </button>
            {% endbuttons %}
        </form>
    {% endif %}
{% endblock content %}

store/templates/stock/details.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
    Details {{ block.super }}
{% endblock %}
{% block content %}
    <br><br>
    <div class="row clearfix">
        <div class="col-md-12 col-sm-12 column">
            <fieldset>
                {% if stock.quantity == 0 %}
                <h3 style="font-weight:bold; color: red">**Out Of Stock**</h3>
                {% endif %}
                <legend class="h2">{{ stock.name }}</legend>
                {% if photos %}
                <div class="row">
                    {% for photo in photos %}
                    <img src="{{ photo.image.url }}" alt="" class="img-rounded img-responsive col-md-6 col-sm-6"/>
                    {% endfor %}
                </div>
                {% endif %}
                <a href="{% url 'user:details' pk=stock.store.owner.pk %}">
                    <strong style="font-size: 2rem;">Store Owner</strong><br>
                </a>
                <span class="glyphicon glyphicon-adjust" aria-hidden="true"></span>
                <b>Gender: </b>{{ stock.store.owner.gender.capitalize }}<br>
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                <b>Rating: </b>{{ stock.store.owner.userrating.current_rating }} Star{{ stock.store.owner.userrating|pluralize }}
                {% if stock.store.owner.userrating.current_rating == 0.0 %}
                <small style="color:red;"><strong>New User</strong></small>
                {% endif %}<br>
                <text style="font-size: 13px;">
                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                        <b>Last seen</b>: {{ stock.store.owner.last_login }}
                </text><br><br>
                <strong style="font-size: 2rem; color: orange">Stock</strong><br>
                {% if user.is_authenticated is False %}
                <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                <b>Location: </b>{{ stock.store.owner.locale.upper }}<br>
                {% endif %}
                <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
                <b>Category: </b>{{ stock.category }}<br>
                {% if request.user == stock.owner %}
                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                <b>Orders: </b>{{ stock.order_set.count }}
                Order{{ stock.order_set.count|pluralize }}<br>
                {% endif %}
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                <b>Available Quantity: </b> {{ stock.quantity }}<br>
                <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
                <b>Price: </b>{{ stock.price }}<br>
                <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
                <strong>Link :</strong>
                    <strong style="color:#77f; whitespace:warp"><br>
                    {{ stock.get_direct_url }}
                    </strong>
                <br><br>
                <strong style="font-size: 2rem; color: orange">Descriptions</strong>
                <blockquote class="h5">
                    {% for line in stock.get_description %}
                        {{ line }}<br>
                    {% endfor %}
                </blockquote>
                <p class="text-right">
                {% if stock.store.owner == user %}
                    <a class="button" href="{% url 'stock:update' pk=stock.pk %}">Update</a>
                    <a class="button" href="{% url 'stock:remove' pk=stock.pk %}">Remove</a>
                    <a class="button" href="{% url 'stock:photo' pk=stock.pk %}">Add Photo</a>
                {% else %}
                    {% if stock.quantity > 0 %}
                    <a class="button" href="{% url 'stock:order' pk=stock.pk %}">
                        Order
                    </a>
                    {% endif %}
                </p>
                {% endif %}
            </fieldset>
            <br><br>
            {% block more %}
            {% if orders %}
                <text class="h3 button">Orders on this Stock</text><br><br>
                {% for order in orders %}
                {% if order.owner == request.user or stock.owner == request.user %}
                <fieldset>
                    <a href="{% url 'user:details' pk=order.owner.pk %}">
                        <h4>{{ order.owner.username }}</h4>
                    </a>
                    <p>
                        <b>Quantity:</b> {{ order.quantity }}<br>
                        {% if order.accepted %}
                            <strong>Accepted: </strong><span class="glyphicon glyphicon-ok" style="color:green;" aria-hidden="true"></span>
                        {% endif %}
                        <small class="sub-text text-left">[ {{ order.order_time }} ]</small>
                    </p>
                    <p class="text-right">
                        {% if stock.store.owner == user %}
                            {% if order.accepted is False %}
                            <a class="button" href="{% url 'order:accept' pk=order.pk %}">
                                Accept
                            </a>
                            {% else %}
                            <a class="button" href="{% url 'order:delete' pk=order.pk %}">
                                Delete
                            </a>
                            {% endif %}
                        <br>
                        {% endif %}
                        {% if order.owner == user %}
                        <a class="button" href="{% url 'order:update' pk=order.pk %}">
                            Update
                        </a>
                        <a class="button" href="{% url 'order:delete' pk=order.pk %}">
                            Delete
                        </a>
                        {% endif %}
                    </p>
                </fieldset>
                {% endif %}
                <br>
                {% endfor %}
            {% endif %}
            {% endblock more %}
        </div>
    </div>
{% endblock content %}

store/templates/stock/form.html
{% extends 'forms.html' %}
{% block title %}
    {{ action }} Stock - {{ block.super }}
{% endblock %}
{% block billboard %}
    <h2>{{ action }} stock</h2>
{% endblock billboard %}
{% block content %}
    <br><br>
    {% if user.is_authenticated %}
        {% block form %}
            {{ block.super }}
        {% endblock form %}
    {% endif %}
{% endblock content %}