bazaar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.views import static
from django.views.generic import TemplateView

from users.views import SignUpView
from users.views import JoinCommunity, RegistrationClosed
from commons.views import home

from search.views import BazaarSearch

urlpatterns = [
    path('', home, name='home'),
    path('welcome/', BazaarSearch.as_view(), name='welcome'),
    path('<locale>/signup/', SignUpView.as_view(), name='signup'),
    path('<locale>/referral/<code>/signup/', SignUpView.as_view(), name='r_signup'),

    path('', include('django.contrib.auth.urls')),
    path('search/', include('haystack.urls')),
    path('password/', include('users.url.password')),
    path('user/', include('users.urls', namespace='user')),
    path('item/', include('items.urls', namespace='item')),
    path('store/', include('store.urls.store', namespace='store')),
    path('stock/', include('store.urls.stock', namespace='stock')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('offer/', include('interest.urls.offer', namespace='offer')),
    path('bargain/', include('interest.urls.bargain', namespace='bargain')),
    path('bookmark/', include('interest.urls.bookmark', namespace='bookmark')),
    path('order/', include('interest.urls.order', namespace='order')),

    path('admin/', admin.site.urls),
    path('join/', JoinCommunity.as_view(), name='join'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('intro/', TemplateView.as_view(template_name='intro.html'), name='intro'),
    path('registration/closed/', RegistrationClosed.as_view(), name='closed'),

]

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', static.serve,
                        {'document_root': settings.MEDIA_ROOT, }
                        ),
                    ]

items/urls.py
from django.urls import path

# My imports -----------------------------------------------------------------
from django.views.generic import TemplateView

from .views import AddItem, ItemInventory, item_home
from .views import ItemDetails, ItemSort
from .views import EditItem, RemoveItem
from .views import ItemReserved, ListItems


from search.views import ItemSearch
from interest.views import AddOffer

app_name = 'item'
urlpatterns = [
    path('', item_home, name='home'),
    path('sort/', TemplateView.as_view(template_name='items/category.html'), name='sort'),
    path('search/', ItemSearch.as_view(), name='search'),

    path('add/', AddItem.as_view(), name='add'),
    path('all/', ListItems.as_view(), name='all'),
    path('inventory/', ItemInventory.as_view(), name='inventory'),

    path('<int:pk>/', ItemDetails.as_view(), name='details'),
    path('<int:pk>/edit/', EditItem.as_view(), name='update'),
    path('<int:pk>/remove/', RemoveItem.as_view(), name='remove'),
    path('<int:pk>/reserved/', ItemReserved.as_view(), name='reserved'),
    path('<int:pk>/interested/', AddOffer.as_view(), name='interested'),

    path('<str:category>/', ItemSort.as_view(), name='category'),
]

users/urls.py
from django.urls import path

from review.views import create_review

from .views import UpdateProfile, DeleteView
from .views import ProfileDetails


app_name = 'user'
urlpatterns = [
    path('<int:pk>/', ProfileDetails.as_view(), name='details'),
    path('<int:pk>/delete/', DeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', UpdateProfile.as_view(), name='update'),
    path('<int:pk>/review/', create_review, name='review_create'),

]

items/models.py
from django.db import models

# Create your models here.
# My imports -----------------------------------------------------------------
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

from cloudinary.models import CloudinaryField


from .constants import CATEGORIES
# =======================================================================


def front_photo_path(instance, filename):
    return '/'.join(['item', str(instance.pk), 'front-'+str(filename)])


def back_photo_path(instance, filename):
    return '/'.join(['item', str(instance.pk), 'back-'+str(filename)])


class Item(models.Model):
    """
    Core model for the Bazaar platform. It represents the value-unit
    exchanged on the platform.
    """
    name = models.CharField(max_length=100,)
    description = models.TextField(default='', blank=True)
    available = models.BooleanField(default=True, blank=True)
    category = models.CharField(max_length=25, choices=CATEGORIES)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, )

    photo_front = CloudinaryField('image', default='https://res.cloudinary.com/ichristwin/image/upload/v1571126185/wmbalgw9rof6jen0ni5q.png')
    photo_back = CloudinaryField('image', default='https://res.cloudinary.com/ichristwin/image/upload/v1571126185/wmbalgw9rof6jen0ni5q.png')

    booked_for = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                                   related_name='%(class)s_booked_for',
                                   verbose_name='Booked for',
                                   null=True, blank=True, )
    date_added = models.DateTimeField(auto_now_add=True, blank=True,)
    last_modified = models.DateTimeField(auto_now=True, blank=True,)
    owner_confirmation = models.BooleanField(default=False)
    buyer_confirmation = models.BooleanField(default=False)

    def __str__(self):
        return "%(category)s: %(name)s" % ({'category': self.category,
                                            'name': self.name})

    def get_absolute_url(self):
        return reverse('item:details', kwargs={'pk': self.pk})

    def get_return_url(self):
        return reverse('item:inventory')

    def get_description(self):
        return self.description.strip().split('**')


# =======================================================================

commons/views.py
from django.shortcuts import render, redirect
# from interest.models import Interest


def home(request):
    if request.user.is_authenticated:
        return redirect('%s:home' % request.user.view)
    else:
        return redirect('welcome')

commons/templates/about.html
{% extends 'base.html' %}
{% block title %} About Go - {{ block.super }}{% endblock %}
{% block content %}
    <fieldset>
        <legend class="h2">About Bazaar</legend>
        Project Bazaar is a web application developed for easy of connecting
        individuals whom seek to create & discover value in items who's value
        has been greatly undervalued in the absence of information
        <br><br>
        The site is merely a prototype version and active participation in the
        feedback process will greatly be appreciated.
        <br><br>
        <strong>Final lunch coming soon!</strong>
    </fieldset>
    <br><hr><br>
    <div class="jumbotron">
        <div class="row">
        <div class="container">
            <span class="glyphicon glyphicon-tasks col-md-4" aria-hidden="true" style="font-size:120px"></span>
            <blockquote class="col-md-8 text-left h4">
                <text class="h2">Create Value:</text>
                <br><br>
                List & Sell what you've got...<br>
                Got Items you no longer need? now watch them turn to cash indeed
            </blockquote>
            {% if user.is_authenticated %}
            <br>
            <a href="{% url 'item:add' %}" style="color:gold" class="button">+Add an item for sale</a>
            {% endif %}
        </div>
        </div>
    </div>
    <br><br>
    <div class="jumbotron">
        <div class="row">
        <div class="container">
            <div class="text-right h4 col-md-8">
                <text class="h2">Discover Value:</text>
                 <br><br>
                Search & Discover a variety of items... <br>
                Be quick to claim the things you love, else they go to he who does!
            </div>
            <blockquote class="col-md-4">
                <span class="glyphicon glyphicon-search" aria-hidden="true" style="font-size:120px"></span>
            </blockquote>
            {% if user.is_authenticated %}
            <br>
            <a href="{% url 'item:search' %}" style="color:gold" class="button">Find items on sale</a>
            {% endif %}
        </div>
        </div>
    </div>
    <br><br>
    <div class="jumbotron">
        <div class="row">
        <div class="container">
            <div  class="col-md-4" style="font-size:70px">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-share-alt" aria-hidden="true" style="font-size:50px"></span>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <br>
            <span class="glyphicon glyphicon-usd" aria-hidden="true"></span>
            </div>
            <blockquote class="col-md-8 text-left h4">
                    <text class="h2">Spread Value:</text>
                <br><br>
                Refer Friends & get them to sell... <br>
                Grab your link & spread the word, for which you'll earn some real reward <br>
            </blockquote>
            {% if user.is_authenticated %}
            <br>
            <a href="{% url 'user:details' pk=user.pk %}" style="color:gold" class="button">Get my link</a>
            {% endif %}
        </div>
        </div>
    </div>
    <hr style="width:80%;">
        <br><br>
        <br><br>
{% endblock %}

commons/templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
{% load humanize %}
{% load bootstrap3 %}
    <head>
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
              crossorigin="anonymous">
        <link rel="stylesheet" href="https://res.cloudinary.com/ichristwin/raw/upload/v1570639143/ggkavkwvziopgncke7np.css">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    </head>
    <body class="{{ user.view }}">
        <header>
            {% block ribbon %}
                <div class="row">
                    <div class="container">
                    {% if user.is_authenticated %}
                    <a class="brand pull-left h4" href="#">
                        <strong>{{ user.view.upper }}S</strong>
                    </a>
                    {% endif %}
                    <ul class="list-inline list-unstyled pull-right small">
                        {% if user.is_authenticated %}
                        <li><a href="{{ user.get_home_url }}">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                            Home</a>
                        </li>
                        <li><a href="{{ user.get_search_url }}">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            Search</a>
                        </li>
                        <li><a href="{% url 'logout' %}">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                            Logout</a>
                        </li>
                        <li><a href="{% url 'user:details' pk=user.pk %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            Profile</a>
                        </li>
                        {% else %}
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'join' %}">Signup</a></li>
                        {% endif %}
                    </ul>
                    </div>
                </div>
            {% endblock ribbon %}
        </header>
        <section id="billboard">
            {% block banner %}
            <div class="jumbotron">
                <div class="container">
                    <div class="row">
                        {% block billboard %}
                        {% if user.is_authenticated %}
                            <div class="text-right">
                                <a class="h1" style="color:gold" href="{% url 'user:details' pk=user.pk %}">#{{ user.alias }}</a>
                                <br>
                                <text class="h5 sub-text">{{ user.username }}</text>
                            </div>
                            <hr style="width:60%">
                            <div class="container h1">
                                <a class="btn btn-lg" style="color:#fff; background-color:orange" href="{% url 'item:all' %}">
                                Buy <span class="glyphicon glyphicon-shopping-cart col-md-4" aria-hidden="true"></span>
                                </a>
                                <a class="btn btn-lg" style="color:#fff; background-color:green;" href="{% url 'item:add' %}">
                                Sell <span class="glyphicon glyphicon-tags col-md-4" aria-hidden="true"></span>
                                </a>
                            </div>
                            <hr style="width:60%">
                            {% if user.store %}
                            <a class="button h3" href="{% url 'store:details' pk=user.store.pk %}">My Store</a>
                            {% else %}
                            <a class="button h3" href="{% url 'store:setup' %}">Setup Store</a>
                            {% endif %}
                        {% endif %}
                        {% endblock billboard %}
                    </div>
                </div>
            </div>
            {% endblock banner %}
        </section>
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-3 col-md-2">
                </div>
                {% if user.is_authenticated %}
                {% block menu %}
                <div class="col-xs-9 col-md-10 round">
                </div>
                {% endblock menu %}
                {% endif %}
            </div>
        </div>
        <br><br><br><br>
        {% block content %}
        {% endblock content %}
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
                crossorigin="anonymous">
        </script>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"
                integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
                crossorigin="anonymous">
        </script>
    </body>
    <br><br><br><br>
    <footer style="text-align: center;">
        <div class="container">
            <br><br>
            <p>
            <text class="h1">
                Your feeedback is precious
            </text><br>
            <text>Don't hesitate to inform us, we anxiously await your response</text>
            <a href="{% url 'about' %}" class="button" style="color:gold">About this site</a>
            </p>
            <br><br>
            <div class="row">
                <div class="col-sm-2 col-md-2"></div>
                <div class="col-sm-4 col-md-4">
                    For complaints & suggestions contact the developer
                    <strong style="color:yellow"> Christwin </strong>on whatsapp
                    <br>
                    <text class="button">+2348081147003</text>
                    <br><br>
                </div>
            </div>
        </div>
    </footer>
</html>

commons/templates/dashboard.html
{% load bootstrap3 %}
{% block title %}
     - {{ block.super }}
{% endblock %}
{% block content %}

commons/templates/forms.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
    {{ block.super }}
{% endblock title %}
{% block form %}
    <br>
<div class="container">
    <form role="form" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% block label %}
                    Done
                {% endblock label %}
            </button>
        {% endbuttons %}
    </form>
</div>
{% endblock form %}

commons/templates/home.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
    Home - {{ block.super }}
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <hr style="width:80%;">
    <div class="row clearfix">
        <fieldset class="jumbotron">
            <a href="{% url 'item:inventory' %}" class="h3">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                My Inventory
            </a>
            <br><text class="h5">Items you have added!</text>
            <br>
            <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
            {{ user.item_set.count }} Item{{ user.item_set.count|pluralize }}<br>
        </fieldset>
        <br><hr><br>
        <fieldset class="jumbotron">
            <a href="{% url 'offer:list' %}" class="h3">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                My Interest
            </a>
            <br>Items you are interested in!
            <br>
            <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
            {{ user.offer_set.count }} Offer{{ user.offer_set.count|pluralize }}<br>
        </fieldset>
        <br><hr><br>
        <fieldset class="jumbotron">
            <a href="{% url 'bookmark:list' %}" class="h3">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                My Bookmarks
            </a>
            <br>Items you have bookmarked!
            <br>
            <span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span>
            {{ user.bookmark.bookmarked }} Bookmark{{ user.offer_set.count|pluralize }}<br>
        </fieldset>
        <br><hr><br>
    </div>
    {% else %}
    {% endif %}
{% endblock content %}

commons/templates/intro.html
{% extends 'base.html' %}
{% block title %}
    Intro - {{ block.super }}
{% endblock %}
{% block billboard %}
    <h1>Welcome to {{ user.locale.upper }} Bazaar!</h1>
    <text class="h3 sub-text">~ Everybody Wins! ~</text>
{% endblock billboard %}
{% block content %}
    <hr style="width:80%;">
    <div class="jumbotron">
        <div class="row">
        <div class="container h1">
        <a class="btn btn-lg" style="color:#fff; background-color:orange" href="{% url 'item:search' %}">
            Buy <span class="glyphicon glyphicon-shopping-cart col-md-4" aria-hidden="true"></span>
        </a>
        <a class="btn btn-lg" style="color:#fff; background-color:green" href="{% url 'item:add' %}">
            Sell <span class="glyphicon glyphicon-gift col-md-4" aria-hidden="true"></span>
        </a>
        </div>
        </div>
    </div>
{% endblock content %}

commons/templates/welcome.html
{% extends 'search/search.html' %}
{% block title %}
    Welcome{{ block.super }}
{% endblock title %}
{% block banner %}
    {% if query %}
    {% else %}
        <div class="jumbotron">
            <div class="container">
                <div class="row">
                    {% block billboard %}
                    <div class="warp-headline">
                        <h1 class="h3 text-center">Welcome to the Great<br>
                            <strong>Bazaar</strong>
                        </h1>
                        <h2 class="text-center"><small>~ Campus Edition ~</small></h2>
                        <hr>
                        <ul class="list-inline list-unstyled text-center">
                        <a class="btn btn-lg" style="color:#fff; background-color:orange" href="{% url 'item:all' %}">
                            Buy <span class="glyphicon glyphicon-shopping-cart col-md-4" aria-hidden="true"></span>
                        </a>
                        <a class="btn btn-lg" style="color:#fff; background-color:green" href="{% url 'item:add' %}">
                            Sell <span class="glyphicon glyphicon-tags col-md-4" aria-hidden="true"></span>
                        </a>
                        </ul>
                    </div>
                    {% endblock billboard %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock banner %}
{% block dashboard %}
{% endblock dashboard %}
{% block content %}
    {{ block.super }}
{% endblock content %}