bazaar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.views import static
from django.views.generic import TemplateView

from users.views import SignUpView
from users.views import JoinCommunity, RegistrationClosed
from commons.views import home

from search.views import BazaarSearch

urlpatterns = [
    path('', home, name='home'),
    path('welcome/', BazaarSearch.as_view(), name='welcome'),
    path('<locale>/signup/', SignUpView.as_view(), name='signup'),
    path('<locale>/referral/<code>/signup/', SignUpView.as_view(), name='r_signup'),

    path('', include('django.contrib.auth.urls')),
    path('search/', include('haystack.urls')),
    path('password/', include('users.url.password')),
    path('user/', include('users.urls', namespace='user')),
    path('item/', include('items.urls', namespace='item')),
    path('store/', include('store.urls.store', namespace='store')),
    path('stock/', include('store.urls.stock', namespace='stock')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('offer/', include('interest.urls.offer', namespace='offer')),
    path('bargain/', include('interest.urls.bargain', namespace='bargain')),
    path('bookmark/', include('interest.urls.bookmark', namespace='bookmark')),
    path('order/', include('interest.urls.order', namespace='order')),

    path('admin/', admin.site.urls),
    path('join/', JoinCommunity.as_view(), name='join'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('intro/', TemplateView.as_view(template_name='intro.html'), name='intro'),
    path('registration/closed/', RegistrationClosed.as_view(), name='closed'),

]

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', static.serve,
                        {'document_root': settings.MEDIA_ROOT, }
                        ),
                    ]

items/urls.py
from django.urls import path

# My imports -----------------------------------------------------------------
from django.views.generic import TemplateView

from .views import AddItem, ItemInventory, item_home
from .views import ItemDetails, ItemSort
from .views import EditItem, RemoveItem
from .views import ItemReserved, ListItems


from search.views import ItemSearch
from interest.views import AddOffer

app_name = 'item'
urlpatterns = [
    path('', item_home, name='home'),
    path('sort/', TemplateView.as_view(template_name='items/category.html'), name='sort'),
    path('search/', ItemSearch.as_view(), name='search'),

    path('add/', AddItem.as_view(), name='add'),
    path('all/', ListItems.as_view(), name='all'),
    path('inventory/', ItemInventory.as_view(), name='inventory'),

    path('<int:pk>/', ItemDetails.as_view(), name='details'),
    path('<int:pk>/edit/', EditItem.as_view(), name='update'),
    path('<int:pk>/remove/', RemoveItem.as_view(), name='remove'),
    path('<int:pk>/reserved/', ItemReserved.as_view(), name='reserved'),
    path('<int:pk>/interested/', AddOffer.as_view(), name='interested'),

    path('<str:category>/', ItemSort.as_view(), name='category'),
]

payment/urls.py
from django.urls import path

from .views import proceed_deposit, confirm_deposit
from .views import cashout_proceed, ConfirmDeposit


app_name = 'payment'
urlpatterns = [
    path('<int:pk>/confirm/', ConfirmDeposit.as_view(), name='confirm'),
#    path('<int:pk>/confirm/', confirm_deposit, name='confirm'),
    path('<int:pk>/<bank>/transfer/', proceed_deposit, name='proceed'),
    path('<int:pk>/cashout/', cashout_proceed, name='cashout'),

]

users/urls.py
from django.urls import path

from review.views import create_review

from .views import UpdateProfile, DeleteView
from .views import ProfileDetails


app_name = 'user'
urlpatterns = [
    path('<int:pk>/', ProfileDetails.as_view(), name='details'),
    path('<int:pk>/delete/', DeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', UpdateProfile.as_view(), name='update'),
    path('<int:pk>/review/', create_review, name='review_create'),

]

items/models.py
from django.db import models

# Create your models here.
# My imports -----------------------------------------------------------------
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

from cloudinary.models import CloudinaryField


from .constants import CATEGORIES
# =======================================================================


def front_photo_path(instance, filename):
    return '/'.join(['item', str(instance.pk), 'front-'+str(filename)])


def back_photo_path(instance, filename):
    return '/'.join(['item', str(instance.pk), 'back-'+str(filename)])


class Item(models.Model):
    """
    Core model for the Bazaar platform. It represents the value-unit
    exchanged on the platform.
    """
    name = models.CharField(max_length=100,)
    description = models.TextField(default='', blank=True)
    available = models.BooleanField(default=True, blank=True)
    category = models.CharField(max_length=25, choices=CATEGORIES)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, )

    photo_front = CloudinaryField('image', default='https://res.cloudinary.com/ichristwin/image/upload/v1571126185/wmbalgw9rof6jen0ni5q.png')
    photo_back = CloudinaryField('image', default='https://res.cloudinary.com/ichristwin/image/upload/v1571126185/wmbalgw9rof6jen0ni5q.png')

    booked_for = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                                   related_name='%(class)s_booked_for',
                                   verbose_name='Booked for',
                                   null=True, blank=True, )
    date_added = models.DateTimeField(auto_now_add=True, blank=True,)
    last_modified = models.DateTimeField(auto_now=True, blank=True,)
    owner_confirmation = models.BooleanField(default=False)
    buyer_confirmation = models.BooleanField(default=False)

    def __str__(self):
        return "%(category)s: %(name)s" % ({'category': self.category,
                                            'name': self.name})

    def get_absolute_url(self):
        return reverse('item:details', kwargs={'pk': self.pk})

    def get_return_url(self):
        return reverse('item:inventory')

    def get_description(self):
        return self.description.strip().split('**')


# =======================================================================

items/forms.py
from django import forms
from django.template.loader import render_to_string

from .models import Item

# ===================================================================


class ItemForm(forms.ModelForm):
    iTemplate = 'items/item_description.txt'
    description = forms.CharField(help_text="**Add information that more accurately Describes your Item",
                                  initial=render_to_string(iTemplate).strip(),
                                  widget=forms.Textarea(attrs={'cols': 35, 'rows': 4, }),
                                  )

    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'photo_front', 'photo_back')
        labels = {'name': 'Item name', 'photo_front': 'Item image (front)',
                  'photo_back': 'Item image (other)', }

items/views.py
from django.shortcuts import render, redirect, reverse

# Create your views here.
# My imports -----------------------------------------------------------------
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.views.generic import CreateView, DetailView
from django.views.generic import UpdateView, DeleteView
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from interest.models import Offer
from review.models import UserRating

from .models import Item
from .forms import ItemForm

# ===================================================================


@login_required
def item_home(request):
    request.user.mode = 'item'
    request.user.save()
    return home(request)


class AddItem(LoginRequiredMixin, CreateView):
    model = Item
    form_class = ItemForm
    template_name = 'items/form.html'
    login_url = 'login'
    context_object_name = 'item'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Add'
        context = super(AddItem, self).get_context_data(**kwargs)
        return context


class ItemDetails(DetailView):
    model = Item
    template_name = 'items/details.html'
    context_object_name = 'item'

    def get_context_data(self, **kwargs):
        """
        Add additional info to the profile page, including reviews,
        and user rating
        """
        item = self.get_object()
        if self.request.user == item.owner:
            kwargs['offers'] = Offer.objects.filter(item=item).order_by('-offer')
        elif self.request.user.is_authenticated:
            kwargs['offers'] = Offer.objects.filter(item=item,
                                                    owner=self.request.user,
                                                    ).order_by('-offer')
        context = super(ItemDetails, self).get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        item = self.get_object()
        if item.available is False:
            return redirect('item:reserved', self.kwargs['pk'])
        else:
            return super().dispatch(request, *args, **kwargs)


class ItemReserved(DetailView):
    model = Item
    template_name = 'items/reserved.html'
    context_object_name = 'item'

    def get_context_data(self, **kwargs):
        """
        Add additional info to the profile page, including reviews,
        and user rating
        """
        item = self.get_object()
        kwargs['offer'] = Offer.objects.get(item=item, accepted=True)
        context = super(ItemReserved, self).get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        item = self.get_object()
        if item.available is False:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect('item:details', self.kwargs['pk'])


class EditItem(LoginRequiredMixin, UpdateView):
    model = Item
    form_class = ItemForm
    template_name = 'items/form.html'
    login_url = 'login'
    context_object_name = 'item'

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Edit'
        context = super(EditItem, self).get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        item = self.get_object()
        if item.owner != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class RemoveItem(LoginRequiredMixin, DeleteView):
    model = Item
    template_name = 'items/delete.html'
    success_url = reverse_lazy('item:inventory')
    login_url = 'login'
    context_object_name = 'item'

    def dispatch(self, request, *args, **kwargs):
        item = self.get_object()
        if item.owner != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class ItemInventory(LoginRequiredMixin, ListView):
    model = Item
    template_name = 'items/inventory.html'
    login_url = 'login'
    context_object_name = 'items'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(owner=self.request.user).order_by('-date_added')


class ItemSort(ListView):
    model = Item
    template_name = 'items/all.html'
    context_object_name = 'items'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(category=self.kwargs['category']).order_by('-date_added')

# ===================================================================


def home(request):
    """This view decides what ur home view is, for starters, its intro"""
    return render(request, 'home.html')


class ListItems(ListView):
    model = Item
    template_name = 'items/all.html'
    context_object_name = 'items'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            queryset = queryset.filter(owner__locale=self.request.user.locale)
        return queryset.filter(available=True).order_by('-date_added')

items/templates/items/all.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %} Available Items - {{ block.super }}{% endblock %}
{% block header %}
    {{ block.super }}
{% endblock header %}
{% block content %}
    <div class="row clearfix">
        <div class="col-md-12 column">
            <a href="{% url 'item:add' %}" class="button pull-right h4">
                <strong>+</strong>Add Item
            </a>
            <a href="{% url 'item:sort' %}" class="button pull-right h4">
                Categories
            </a>
            <br><br>
            <text class="h2 button">Available Items</text>
            {% if items %}
            {% for item in items %}
                <hr>
            <fieldset>
                {% if item.available == False %}
                <h3 style="font-weight:bold; color: red">**SOLD**</h3>
                {% endif %}
                <legend class="h2">
                    <a href="{% url 'item:details' pk=item.pk %}">
                        {{ item.name }}
                    </a>
                </legend>
                <a href="{% url 'item:details' pk=item.pk %}">
                    <div class="row">
                        <img src="{{ item.photo_front.url }}" alt="" class="img-rounded img-responsive col-md-6 col-sm-6"/>
                        <img src="{{ item.photo_back.url }}" alt="" class="img-rounded img-responsive col-md-6 col-sm-6"/>
                    </div>
                </a>
                <br><br>
                <strong style="font-size: 2rem; color: orange">Item</strong><br>
                {% if user.is_authenticated is False %}
                <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                <b>Location: </b>{{ item.owner.locale.upper }}<br>
                {% endif %}
                <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
                <b>Category: </b>{{ item.category }}<br>
                <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
                <b>Interest: </b>
                <strong style="color:#77f;">
                {{ item.offer_set.count }}
                Offer{{ item.offer_set.count|pluralize }}
                </strong><br>
                <strong style="font-size: 2rem; color: orange">Descriptions</strong>
                <blockquote class="h5">
                    {% for line in item.get_description %}
                        {{ line }}<br>
                    {% endfor %}
                </blockquote>
                <p class="text-right">
                {% if item.owner == user %}
                    <a class="button" href="{% url 'item:update' pk=item.pk %}">Update</a>
                    <a class="button" href="{% url 'item:remove' pk=item.pk %}">Remove</a>
                {% else %}
                    {% if item.available %}
                    <a class="button" href="{% url 'item:interested' pk=item.pk %}">
                        I'm Interested
                    </a>
                    {% endif %}
                </p>
                {% endif %}
            </fieldset>
            <br><br>
            {% endfor %}
            {% else %}
            <hr>
            No items to show!
            {% endif %}
        </div>
    </div>
{% endblock content %}

items/templates/items/category.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %} Item Categories - {{ block.super }}{% endblock %}
{% block header %}
    {{ block.super }}
{% endblock header %}
{% block content %}
<div class="container">
    <ul class="list-unstyled" style="text-align: center;">
        <li>
            <a href="{% url 'item:category' category='bags' %}" class="h2 button">Bags</a>
        </li>
        <br>
        <li>
            <a href="{% url 'item:category' category='books' %}" class="h2 button">Books</a>
        </li>
        <br>
        <li>
            <a href="{% url 'item:category' category='shoes' %}" class="h2 button">Shoes</a>
        </li>
        <br>
        <li>
            <a href="{% url 'item:category' category='cloths' %}" class="h2 button">Cloths</a>
        </li>
        <br>
        <li>
            <a href="{% url 'item:category' category='utensils' %}" class="h2 button">Utensils</a>
        </li>
        <br>
        <li>
            <a href="{% url 'item:category' category='jeweleries' %}" class="h2 button">Jeweleries</a>
        </li>
        <br>
        <li>
            <a href="{% url 'item:category' category='phones' %}" class="h2 button">Mobile Phones</a>
        </li>
        <br>
        <li>
            <a href="{% url 'item:category' category='electronics' %}" class="h2 button">Electronics</a>
        </li>
        <br>
        <li>
            <a href="{% url 'item:category' category='laptops' %}" class="h2 button">Laptop Computers</a>
        </li>
        <br>
        <li>
            <a href="{% url 'item:category' category='furniture' %}" class="h2 button">Furniture</a>
        </li>
        <br>
        <li>
            <a href="{% url 'item:category' category='cosmetics' %}" class="h2 button">Cosmetics</a>
        </li>
    </ul>
</div>
{% endblock content %}

items/templates/items/delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
    Remove Item - {{ block.super }}
{% endblock title %}
{% block content %}
    {% if user.is_authenticated %}
    <h1>Remove Item</h1>
    <p>Are you sure you want to remove
        <b>Item: {{ object.name }}</b>?
    </p>
        <form action="" method="post">
            {% csrf_token %}
            {% buttons %}
                <button type="submit" class="btn btn-danger">
                    Yes! remove
                </button>
            {% endbuttons %}
        </form>
    {% endif %}
{% endblock content %}

items/templates/items/details.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
    Details {{ block.super }}
{% endblock %}
{% block content %}
    <br><br>
    <div class="row clearfix">
        <div class="col-md-12 col-sm-12 column">
            <fieldset>
                {% if item.available == False %}
                <h3 style="font-weight:bold; color: red">**SOLD**</h3>
                {% endif %}
                <legend class="h2">{{ item.name }}</legend>
                <div class="row">
                    <img src="{{ item.photo_front.url }}" alt="" class="img-rounded img-responsive col-md-6 col-sm-6"/>
                    <img src="{{ item.photo_back.url }}" alt="" class="img-rounded img-responsive col-md-6 col-sm-6"/>
                </div>
                <a href="{% url 'user:details' pk=item.owner.pk %}">
                    <strong style="font-size: 2rem;">Owner</strong><br>
                </a>
                {% if user.is_authenticated and user != item.owner %}
                <a href="{% url 'bookmark:add' pk=item.pk %}" class="pull-right button h2">
                    <span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span> +
                </a>
                {% endif %}
                <span class="glyphicon glyphicon-adjust" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                <b>Rating: </b>{{ item.owner.userrating.current_rating }} Star{{ item.owner.userrating|pluralize }}
                {% if item.owner.userrating.current_rating == 0.0 %}
                <small style="color:red;"><strong>New User</strong></small>
                {% endif %}<br>
                <text style="font-size: 13px;">
                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                        <b>Last seen</b>: {{ item.owner.last_login }}
                </text><br><br>
                <strong style="font-size: 2rem; color: orange">Item</strong><br>
                {% if user.is_authenticated is False %}
                <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                <b>Location: </b>{{ item.owner.locale.upper }}<br>
                {% endif %}
                <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
                <b>Category: </b>{{ item.category }}<br>
                <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
                <b>Interest: </b>
                <strong style="color:#77f;">
                {{ item.offer_set.count }}
                Offer{{ item.offer_set.count|pluralize }}
                </strong><br>
                <strong style="font-size: 2rem; color: orange">Descriptions</strong>
                <blockquote class="h5">
                    {% for line in item.get_description %}
                        {{ line }}<br>
                    {% endfor %}
                </blockquote>
                <p class="text-right">
                {% if item.owner == user %}
                    <a class="button" href="{% url 'item:update' pk=item.pk %}">Update</a>
                    <a class="button" href="{% url 'item:remove' pk=item.pk %}">Remove</a>
                {% else %}
                    {% if item.available %}
                    <a class="button" href="{% url 'item:interested' pk=item.pk %}">
                        I'm Interested
                    </a>
                    {% endif %}
                </p>
                {% endif %}
            </fieldset>
            <br><br>
            {% block more %}
            {% if offers %}
                <text class="h3 button">Offers on this Item</text><br><br>
                {% for offer in offers %}
                <fieldset>
                    <a href="{% url 'user:details' pk=offer.owner.pk %}">
                        <h4>#{{ offer.owner.alias }}</h4>
                    </a>
                    <p>
                        <b>Offer:</b> {{ offer.offer }} NGN<br>
                        <small class="sub-text text-left">[ {{ offer.last_modified }} ]</small>
                    </p>
                    <p class="text-right">
                        {% if item.owner == user %}
                        <a class="button" href="{% url 'offer:accept' pk=offer.pk %}">
                            Accept
                        </a>
                        <a class="button" href="{% url 'bargain:add' pk=offer.pk%}">
                            Bargain
                        </a>
                        <br>
                        {% endif %}
                        {% if offer.owner == user %}
                        <a class="button" href="{% url 'offer:update' pk=offer.pk %}">
                            Update
                        </a>
                        <a class="button" href="{% url 'offer:delete' pk=offer.pk %}">
                            Delete
                        </a>
                        {% endif %}
                    </p>
                        {% if offer.bargain %}
                        <hr style="width:100%">
                        <blockquote class="pull-left h5">
                            <b style="color: orange">Seller's Bargain: </b>
                            {{ offer.bargain.bargain }} NGN
                            <br><br>
                            {% if offer.owner == user %}
                            <a class="button" href="{% url 'bargain:accept' pk=offer.pk %}">
                                Accept
                            </a><br>
                            {% endif %}
                            {% if offer.bargain.seller == user %}
                            <a class="button" href="{% url 'bargain:update' pk=offer.bargain.pk %}">
                                Update
                            </a>
                            <a class="button" href="{% url 'bargain:delete' pk=offer.bargain.pk %}">
                                Delete
                            </a><br>
                            {% endif %}
                        </blockquote>
                        {% endif %}
                </fieldset>
                <br>
                {% endfor %}
            {% endif %}
            {% endblock more %}
        </div>
    </div>
{% endblock content %}

items/templates/items/form.html
{% extends 'forms.html' %}
{% block title %}
    {{ action }} Item - {{ block.super }}
{% endblock %}
{% block billboard %}
    <h2>{{ action }} Item</h2>
{% endblock billboard %}
{% block content %}
    <br><br>
    {% if user.is_authenticated %}
        {% block form %}
            {{ block.super }}
        {% endblock form %}
    {% endif %}
{% endblock content %}

items/templates/items/inventory.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %} My Inventory - {{ block.super }}{% endblock %}
{% block header %}
    {{ block.super }}
{% endblock header %}
{% block content %}
{% if user.is_authenticated %}
    <div class="row clearfix">
        <div class="col-md-12 column">
            <a href="{% url 'item:add' %}" class="button pull-right h4">
                <strong>+</strong>Add Item
            </a>
            <br><br>
            <text class="h2 button">My Inventory</text>
            {% if items %}
                {% for item in items %}
                <hr>
                <h3 style="text-transform:uppercase;">
                    <a href="{% url 'item:details' pk=item.pk %}">
                        {{ item.name }}
                    </a>
                    <br>
                </h3>
                <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
                <b>Category: </b>{{ item.category }}<br>
                <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
                <b>Interest: </b>{{ item.offer_set.count }}
                Offer{{ item.offer_set.count|pluralize }}<br>
                <b>Available: </b>
                {% if item.available %}
                <span class="glyphicon glyphicon-ok" style="color:green;" aria-hidden="true"></span>
                {% else %}
                <span class="glyphicon glyphicon-remove" style="color:red;"  aria-hidden="true"></span>
                {% endif %}
                <br>
                {% endfor %}
            <hr>
            {% else %}
            <hr>
            No items to show!
            {% endif %}
        </div>
    </div>
{% endif %}
{% endblock content %}

items/templates/items/reserved.html
{% extends 'items/details.html' %}
{% load bootstrap3 %}
{% block title %}
    {{ block.super }}
{% endblock %}
{% block more %}
    <fieldset>
        <a href="{% url 'user:details' pk=offer.owner.pk %}">
            <h4>#{{ offer.owner.alias }}</h4>
        </a>
        <p>
        <h4 style="font-style:italic; font-weight:bold; color: green">**Accepted**</h4>
        <b>Offer:</b> {{ offer.offer }}
        <br>
        {% if offer.collectdeposit.received %}
        <h4 style="font-style:italic; font-weight:bold; color: Gold">**Received Payment**</h4>
        {% endif %}
        <small class="sub-text text-left">[ {{ offer.last_modified }} ]</small>
        <p class="text-right">
            {% if item.owner == user or offer.owner == user %}
            <a class="button" href="{% url 'offer:cancel' pk=offer.pk%}">
                Cancel acceptance
            </a>
            {% endif %}
            {% if offer.owner == user %}
            <a class="button" href="{% url 'payment:proceed' pk=offer.pk bank='bank' %}">
                Proceed Transaction
            </a>
            {% endif %}
            {% if item.owner == user %}
            <a class="button" href="{% url 'payment:cashout' pk=offer.pk %}">
                Setup cashout
            </a>
            {% endif %}
        </p>
    </fieldset><br>
{% endblock more %}