bazaar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.views import static
from django.views.generic import TemplateView

from users.views import SignUpView
from users.views import JoinCommunity, RegistrationClosed
from commons.views import home

from search.views import BazaarSearch

urlpatterns = [
    path('', home, name='home'),
    path('welcome/', BazaarSearch.as_view(), name='welcome'),
    path('<locale>/signup/', SignUpView.as_view(), name='signup'),
    path('<locale>/referral/<code>/signup/', SignUpView.as_view(), name='r_signup'),

    path('', include('django.contrib.auth.urls')),
    path('search/', include('haystack.urls')),
    path('password/', include('users.url.password')),
    path('user/', include('users.urls', namespace='user')),
    path('item/', include('items.urls', namespace='item')),
    path('store/', include('store.urls.store', namespace='store')),
    path('stock/', include('store.urls.stock', namespace='stock')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('offer/', include('interest.urls.offer', namespace='offer')),
    path('bargain/', include('interest.urls.bargain', namespace='bargain')),
    path('bookmark/', include('interest.urls.bookmark', namespace='bookmark')),
    path('order/', include('interest.urls.order', namespace='order')),

    path('admin/', admin.site.urls),
    path('join/', JoinCommunity.as_view(), name='join'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('intro/', TemplateView.as_view(template_name='intro.html'), name='intro'),
    path('registration/closed/', RegistrationClosed.as_view(), name='closed'),

]

if settings.DEBUG:
    urlpatterns += [url(r'^media/(?P<path>.*)$', static.serve,
                        {'document_root': settings.MEDIA_ROOT, }
                        ),
                    ]

items/urls.py
from django.urls import path

# My imports -----------------------------------------------------------------
from django.views.generic import TemplateView

from .views import AddItem, ItemInventory, item_home
from .views import ItemDetails, ItemSort
from .views import EditItem, RemoveItem
from .views import ItemReserved, ListItems


from search.views import ItemSearch
from interest.views import AddOffer

app_name = 'item'
urlpatterns = [
    path('', item_home, name='home'),
    path('sort/', TemplateView.as_view(template_name='items/category.html'), name='sort'),
    path('search/', ItemSearch.as_view(), name='search'),

    path('add/', AddItem.as_view(), name='add'),
    path('all/', ListItems.as_view(), name='all'),
    path('inventory/', ItemInventory.as_view(), name='inventory'),

    path('<int:pk>/', ItemDetails.as_view(), name='details'),
    path('<int:pk>/edit/', EditItem.as_view(), name='update'),
    path('<int:pk>/remove/', RemoveItem.as_view(), name='remove'),
    path('<int:pk>/reserved/', ItemReserved.as_view(), name='reserved'),
    path('<int:pk>/interested/', AddOffer.as_view(), name='interested'),

    path('<str:category>/', ItemSort.as_view(), name='category'),
]

users/urls.py
from django.urls import path

from review.views import create_review

from .views import UpdateProfile, DeleteView
from .views import ProfileDetails


app_name = 'user'
urlpatterns = [
    path('<int:pk>/', ProfileDetails.as_view(), name='details'),
    path('<int:pk>/delete/', DeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', UpdateProfile.as_view(), name='update'),
    path('<int:pk>/review/', create_review, name='review_create'),

]

store/models.py
from django.db import models

# Create your models here.
# My imports -----------------------------------------------------------------
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

import cloudinary
from cloudinary.models import CloudinaryField

from django.dispatch import receiver
from django.db.models.signals import pre_delete

from .constants import CATEGORIES
# =======================================================================

DOMAIN = getattr(settings, 'DOMAIN', 'localhost')


def front_photo_path(instance, filename):
    return '/'.join(['item', str(instance.pk), 'front-'+str(filename)])


def back_photo_path(instance, filename):
    return '/'.join(['item', str(instance.pk), 'back-'+str(filename)])

# =======================================================================


class Store(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(default='', blank=True)
    owner = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, )
    is_verified = models.BooleanField(default=False, blank=True)

    def get_absolute_url(self):
        return reverse("store:details", kwargs={'pk': self.pk})

    def get_direct_url(self):
        return DOMAIN+reverse("store:details", kwargs={'pk': self.pk})


class Stock(models.Model):
    name = models.CharField(max_length=100,)
    description = models.TextField(default='', blank=True)
    price = models.PositiveSmallIntegerField()
    category = models.CharField(max_length=25, choices=CATEGORIES)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, )
    quantity = models.PositiveSmallIntegerField(default=2)

    date_added = models.DateTimeField(auto_now_add=True, blank=True,)
    orders = models.ManyToManyField(get_user_model(), related_name='orders', )

    def __str__(self):
        return "%(category)s: %(name)s" % ({'category': self.category,
                                            'name': self.name})

    def get_absolute_url(self):
        return reverse('stock:details', kwargs={'pk': self.pk})

    def get_return_url(self):
        return reverse('stock', kwargs={'pk': self.store.pk})

    def get_description(self):
        return self.description.strip().split('**')

    def get_direct_url(self):
        return DOMAIN+reverse("stock:details", kwargs={'pk': self.pk})


class CloudinaryPhoto(models.Model):
    image = CloudinaryField('image')
    stock = models.OneToOneField(Stock, on_delete=models.CASCADE, )


@receiver(pre_delete, sender=CloudinaryPhoto)
def photo_delete(sender, instance, **kwargs):
    cloudinary.uploader.destroy(instance.image.public_id)

store/forms.py
from django import forms
from django.template.loader import render_to_string
from django.forms import ModelForm

from .models import Store, Stock
from .models import CloudinaryPhoto

# ===================================================================


class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = ('name', 'description', )
        labels = {'name': 'Store name', }


class StockForm(forms.ModelForm):
    iTemplate = 'items/item_description.txt'
    description = forms.CharField(help_text="**Add information that more accurately Describes your Item",
                                  initial=render_to_string(iTemplate).strip(),
                                  widget=forms.Textarea(attrs={'cols': 35, 'rows': 4, }),
                                  )

    class Meta:
        model = Stock
        fields = ('category', 'name', 'description', 'quantity', 'price')
        labels = {'name': 'Item name', }


class StockUpdateForm(StockForm):
    class Meta(StockForm.Meta):
        fields = ('category', 'name', 'description', 'quantity', 'price',)


class CloudinaryPhotoForm(ModelForm):
    class Meta:
        model = CloudinaryPhoto
        fields = ('image', )

store/views.py
from django.shortcuts import render, redirect, reverse

# Create your views here.
# My imports -----------------------------------------------------------------
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.views.generic import CreateView, DetailView
from django.views.generic import UpdateView, DeleteView
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import CloudinaryPhotoForm
from .models import CloudinaryPhoto

from interest.models import Order
from review.models import UserRating

from .models import Store, Stock
from .forms import StoreForm
from .forms import StockForm, StockUpdateForm

# ===================================================================


@login_required
def store_home(request):
    request.user.mode = 'store'
    request.user.save()
    return home(request)


class SetupStore(LoginRequiredMixin, CreateView):
    model = Store
    form_class = StoreForm
    template_name = 'store/form.html'
    login_url = 'login'
    context_object_name = 'store'

    def get_success_url(self):
        return reverse_lazy('store:details', kwarg={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Setup'
        context = super(SetupStore, self).get_context_data(**kwargs)
        return context


class StoreDetails(DetailView):
    model = Store
    template_name = 'store/details.html'
    context_object_name = 'store'

    def get_context_data(self, **kwargs):
        """
        Add additional info to the profile page, including reviews,
        and user rating
        """
        store = self.get_object()
        kwargs['stocks'] = store.stock_set.all().order_by('-date_added')
        context = super(StoreDetails, self).get_context_data(**kwargs)
        return context


class UpdateStore(LoginRequiredMixin, UpdateView):
    model = Store
    form_class = StoreForm
    template_name = 'store/form.html'
    login_url = 'login'
    context_object_name = 'store'

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Update'
        context = super(UpdateStore, self).get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        store = self.get_object()
        if store.owner != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class DeleteStore(LoginRequiredMixin, DeleteView):
    model = Store
    template_name = 'store/delete.html'
    success_url = reverse_lazy('home')
    login_url = 'login'
    context_object_name = 'store'

    def dispatch(self, request, *args, **kwargs):
        store = self.get_object()
        if store.owner != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


# ===================================================================


class AddStock(LoginRequiredMixin, CreateView):
    model = Stock
    form_class = StockForm
    template_name = 'stock/form.html'
    login_url = 'login'
    context_object_name = 'store'

    def post(self, request, *args, **kwargs):
        response = super(AddStock, self).post(request, *args, **kwargs)
        return response

    def form_valid(self, form):
        form.instance.store = self.request.user.store
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Add'
        context = super(AddStock, self).get_context_data(**kwargs)
        return context


class StockDetails(DetailView):
    model = Stock
    template_name = 'stock/details.html'
    context_object_name = 'stock'

    def get_context_data(self, **kwargs):
        """
        Add additional info to the profile page, including reviews,
        and user rating
        """
        stock = self.get_object()
        kwargs['photos'] = CloudinaryPhoto.objects.filter(stock=stock)
        if self.request.user == stock.store.owner:
            kwargs['orders'] = Order.objects.filter(stock=stock).order_by('-order_time')
        elif self.request.user.is_authenticated:
            kwargs['orders'] = Order.objects.filter(stock=stock,
                                                    owner=self.request.user,
                                                    ).order_by('-order_time')
        context = super(StockDetails, self).get_context_data(**kwargs)
        return context


class UpdateStock(LoginRequiredMixin, UpdateView):
    model = Stock
    form_class = StockUpdateForm
    template_name = 'stock/form.html'
    login_url = 'login'
    context_object_name = 'store'

    def get_context_data(self, **kwargs):
        kwargs['action'] = 'Update'
        context = super(UpdateStock, self).get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        stock = self.get_object()
        if stock.store.owner != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class RemoveStock(LoginRequiredMixin, DeleteView):
    model = Stock
    template_name = 'stock/delete.html'
    success_url = reverse_lazy('store:store')
    login_url = 'login'
    context_object_name = 'store'

    def dispatch(self, request, *args, **kwargs):
        stock = self.get_object()
        if stock.store.owner != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


# ===================================================================


def home(request):
    """This view decides what ur home view is, for starters, its intro"""
    return render(request, 'home.html')


def add_photo(request, pk):
    if request.method == "POST":
        form = CloudinaryPhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.stock = Stock.objects.get(pk=pk)
            photo.save()
            return redirect('stock:details', pk)
    else:
        form = CloudinaryPhotoForm()
    return render(request, 'store/form.html', {'form': form})

store/templates/store/all.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %} Available Items - {{ block.super }}{% endblock %}
{% block header %}
    {{ block.super }}
{% endblock header %}
{% block content %}
    <div class="row clearfix">
        <div class="col-md-12 column">
            <a href="{% url 'item:add' %}" class="button pull-right h4">
                <strong>+</strong>Add Item
            </a>
            <br><br>
            <text class="h2 button">Available Items</text>
            {% if items %}
                {% for item in items %}
                <hr>
            <fieldset>
                <h3 style="text-transform:uppercase;">
                    <a href="{% url 'item:details' pk=item.pk %}">
                        {{ item.name }}
                    </a>
                    <br>
                </h3>
                <strong style="font-size: 2rem; color: orange">Owner</strong><br>
                <span class="glyphicon glyphicon-adjust" aria-hidden="true"></span>
                <b>Gender: </b>{{ item.owner.gender.capitalize }}<br>
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                <b>Rating: </b>{{ item.owner.userrating.current_rating }} Star{{ profile.userrating|pluralize }}<br>
                <text style="font-size: 13px;">
                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                    <b>Last seen</b>: {{ item.owner.last_login }}
                </text><br><br>
                <strong style="font-size: 2rem; color: orange">Item</strong><br>
                {% if user.is_authenticated is False %}
                <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                <b>Location: </b>{{ item.owner.locale.upper }}<br>
                {% endif %}
                <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
                <b>Category: </b>{{ item.category }}<br>
                <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
                <b>Interest: </b>{{ item.offer_set.count }}
                Offer{{ item.offer_set.count|pluralize }}<br>
                <b>Available: </b>
                {% if item.available %}
                <span class="glyphicon glyphicon-ok" style="color:green;" aria-hidden="true"></span>
                {% else %}
                <span class="glyphicon glyphicon-remove" style="color:red;"  aria-hidden="true"></span>
                {% endif %}
                <br>
                {% endfor %}
            </fieldset><br><br>
            {% else %}
            <hr>
            No items to show!
            {% endif %}
        </div>
    </div>
{% endblock content %}

store/templates/store/delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
    Remove store - {{ block.super }}
{% endblock title %}
{% block content %}
    {% if user.is_authenticated %}
    <h1>Remove Store</h1>
    <p>Are you sure you want to remove
        <b>Store: {{ object.name }}</b>?
    </p>
        <form action="" method="post">
            {% csrf_token %}
            {% buttons %}
                <button type="submit" class="btn btn-danger">
                    Yes! remove
                </button>
            {% endbuttons %}
        </form>
    {% endif %}
{% endblock content %}

store/templates/store/details.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
    Details {{ block.super }}
{% endblock %}
{% block content %}
    <br><br>
    <div class="row clearfix">
        <div class="col-md-12 col-sm-12 column">
            <fieldset>
                <legend class="h2">{{ store.name }}</legend>
                <a href="{% url 'user:details' pk=store.owner.pk %}">
                    <strong style="font-size: 2rem;">Owner</strong><br>
                </a>
                {% if user.is_authenticated and user != store.owner %}
                <a href="{% url 'bookmark:add' pk=store.pk %}" class="pull-right button h1">
                    <span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span>+
                </a>
                {% endif %}
                <span class="glyphicon glyphicon-adjust" aria-hidden="true"></span>
                <b>Gender: </b>{{ store.owner.gender.capitalize }}<br>
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                <b>Rating: </b>{{ store.owner.userrating.current_rating }} Star{{ store.owner.userrating|pluralize }}
                {% if store.owner.userrating.current_rating == 0.0 %}
                <small style="color:red;"><strong>New User</strong></small>
                {% endif %}<br>
                <text style="font-size: 13px;">
                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                        <b>Last seen</b>: {{ store.owner.last_login }}
                </text><br><br>
                <strong style="font-size: 2rem; color: orange">Stock</strong><br>
                {% if user.is_authenticated is False %}
                <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                <b>Location: </b>{{ store.owner.locale.upper }}<br>
                {% endif %}
                <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
                <b>Stock: </b>{{ store.stock_set.count }}
                Stock{{ store.stock_set.count|pluralize }}<br>
                <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
                <strong>Link :</strong>
                    <strong style="color:#77f; whitespace:warp"><br>
                    {{ store.get_direct_url }}
                    </strong>
                <br><br>
                <strong style="font-size: 2rem; color: orange">Descriptions</strong>
                <blockquote class="h5">
                    {{ store.description }}
                </blockquote>
                <p class="text-right">
                {% if store.owner == user %}
                    <a class="button" href="{% url 'store:update' pk=store.pk %}">Update</a>
                    <a class="button" href="{% url 'store:delete' pk=store.pk %}">Remove</a>
                {% endif %}
            </fieldset>
            {% if store.owner == user %}
            <a href="{% url 'stock:add' %}" class="button pull-right h4">
                <strong>+</strong>Add Stock
            </a>
            {% endif %}
            <br><br>
            {% block more %}
            {% if store.stock_set.all %}
                <text class="h3 button">This Store's Stock</text><br><br>
                {% for stock in store.stock_set.all %}
                <fieldset>
                    <h3 style="text-transform:uppercase;">
                        <a href="{% url 'stock:details' pk=stock.pk %}">
                        {{ stock.name }}
                        </a>
                    </h3>
                    <strong style="font-size: 2rem; color: orange">Descriptions</strong>
                    <blockquote class="h5">
                        {% for line in stock.get_description %}
                            {{ line }}<br>
                        {% endfor %}
                    </blockquote>
                    <strong>Price: </strong><text>{{ stock.price }}</text>
                </fieldset>
                <br>
                {% endfor %}
            {% endif %}
            {% endblock more %}
        </div>
    </div>
{% endblock content %}

store/templates/store/form.html
{% extends 'forms.html' %}
{% block title %}
    {{ action }} Store - {{ block.super }}
{% endblock %}
{% block billboard %}
    <h2>{{ action }} Store</h2>
{% endblock billboard %}
{% block content %}
    <br><br>
    {% if user.is_authenticated %}
        {% block form %}
            {{ block.super }}
        {% endblock form %}
    {% endif %}
{% endblock content %}